### ISSUE TITLE
deploy not finding afrilearndata

### ISSUE THREAD

**Issue by andysouth** [afrimapr/afrimapr-book#10]
deploy is not finding afrilearndata.

It is specified as a remotes in Description.

I see a line here that says it should install book dependencies, but seems not to be working.  
https://github.com/afrimapr/afrimapr-book/blob/b0fe0d88a436021898124f33c1026647f6ad4c5c/.github/workflows/tic.yml#L121

Thanks :-)

https://github.com/afrimapr/afrimapr-book/blob/b0fe0d88a436021898124f33c1026647f6ad4c5c/01-intro.Rmd#L27

Error: Error: A step failed in stage "deploy": deploy. 
Execution halted there is no package called 'afrilearndata'

**Comment by Robinlovelace** [comment]
See here for info on how to add packages: https://github.com/afrimapr/afrimapr-book/commit/8d3d8f38e41438d64898b4cf63e773d5c2630991

**Comment by andysouth** [comment]
Hi @Robinlovelace @martynabogacz I don't think that solves it. The afrilearndata package is already added under the remotes section in the Description file.

**Comment by martynabogacz** [comment]
Hello,

Unfortunately yes, I tried it too and it failed.

Will keep trying.

Martyna

On 11.12.2020, at 17:52, Andy South <notifications@github.com> wrote:

﻿

Hi @Robinlovelace<https://github.com/Robinlovelace> @martynabogacz<https://github.com/martynabogacz> I don't think that solves it. The afrilearndata package is already added under the remotes section in the Description file.

**Comment by Robinlovelace** [comment]
> Hi @Robinlovelace @martynabogacz I don't think that solves it. The afrilearndata package is already added under the remotes section in the Description file.

Hi @andysouth I think you need to add the package to both `Imports` and `Remotes`, as described here https://cran.r-project.org/web/packages/devtools/vignettes/dependencies.html and as done in https://github.com/afrimapr/afrimapr-book/commit/8d3d8f38e41438d64898b4cf63e773d5c2630991

Currently it seems `afrilearndata` is only in the Remotes section:

https://github.com/afrimapr/afrimapr-book/blob/5b628fcc8c3e2627bf1f716e58c478e4855966a5/DESCRIPTION#L28-L39

I don't think the the `afrimaprbook` entry is needed.

**Comment by andysouth** [comment]
Thanks @Robinlovelace @martynabogacz yes, putting into both `Imports` and `Remotes` fixed it, book compiling now :-)

**Comment by Robinlovelace** [comment]
Great work @andysouth, to be fair it's not clear and I think many people (including myself) have walked into that. Thanks for fast fix!
