### ISSUE TITLE
Problem with publisging the book since new release of R version

### ISSUE THREAD

**Issue by martynabogacz** [afrimapr/afrimapr-book#14]
I have not changed anything significant but now when I try to push the change it fails nearly instantly and the error message states the following:

Run r-lib/actions/setup-r@master
Error: Failed to get R 4.0.4: Failed to get R 4.0.4: Failed to download version 4.0.4: Error: Unexpected HTTP response: 403

I updated my R version but it didn't help. I would appreciate if you could have a look when you have a free moment.

**Comment by Robinlovelace** [comment]
Think this is sorted now.
