### ISSUE TITLE
Problem with deployment and remotes package

### ISSUE THREAD

**Issue by martynabogacz** [afrimapr/afrimapr-book#15]
Hi, I sorted problem with missing packages but still one failure is remaining when it tries to build a book. It happened when I included this command: remotes::install_github("afrimapr/afrilearndata").  I think I messed something up with remotes package and cannnot restore previous settings.

Please see the error message here: https://github.com/afrimapr/afrimapr-book/runs/1994716995?check_suite_focus=true#step:21:1287

Moreover problem here: https://github.com/afrimapr/afrimapr-book/runs/1994716990#step:4:2248 

Thanks

**Comment by Robinlovelace** [comment]
Interesting. I am confident I know the cause of at least one of the issues now: the latest version of `tmap` is causing issues here I think: https://github.com/afrimapr/afrimapr-book/runs/2002434235

So may be worth turning off `tmap` code for now. Heads-up @mtennekes, I think this is the same as the issue described here: https://github.com/mtennekes/tmap/issues/551

Sorry for the lack of reprex here but the 'NA' issue seems the same.

**Comment by martynabogacz** [comment]
Yes, you were right. As soon as I commented out all the tmap related code, it worked. Thansk a lot. I would be interested in knowing how you knew it was a tmap package problem?

Thanks!

**Comment by Robinlovelace** [comment]
It was the link in this issue: https://github.com/mtennekes/tmap/issues/551

Thank links to this issue: https://github.com/ropensci/stats19/issues/190

Which in turn links to this: https://cran.r-project.org/web/checks/check_results_stats19.html

On that page it says:

```
     Quitting from lines 953-962 (stats19-training.Rmd) 
```

That was: https://github.com/ropensci/stats19/blob/441d5d603d44bb24c991dab5427401c2d42406e7/vignettes/stats19-training.Rmd#L953-L960

Given that `tmap` has been changing recently I guessed that it was more likely than `plot()` to be causing the issue. Confirmed on my computer.

Quite an adventure and not an easy to debug!

**Comment by Robinlovelace** [comment]
And in terms of the messages on this repo, I recognised this error message: https://github.com/afrimapr/afrimapr-book/runs/2002434235#step:4:2187
