### ISSUE TITLE
Missing html dependency for mapview

### ISSUE THREAD

**Issue by martynabogacz** [afrimapr/afrimapr-book#22]
When I try to use mapview package the issue with deployment emerges. The error shows some issues with missing "html_dependency", as described here:
https://github.com/afrimapr/afrimapr-book/runs/2298605950#step:21:1931

**Comment by andysouth** [comment]
Looks like @Robinlovelace had experience of this issue with geocompr 

A newer potential hack/solution is here : https://github.com/arc2r/book/commit/ef29b157e6ecd56f2baeccd5141bf3d213f914d1

**Comment by martynabogacz** [comment]
Mapview seems to be working now with new deployment service (Netlify).
