### ISSUE TITLE
Actions are failing

### ISSUE THREAD

**Issue by andysouth** [afrimapr/afrimapr-book#23]
https://github.com/afrimapr/afrimapr-book/runs/2445572841?check_suite_focus=true

I don't think I changed anything other than text. Have we seen this before @martynabogacz ?

**Comment by andysouth** [comment]
This error is generated by bookdown here : https://github.com/rstudio/bookdown/blob/master/R/render.R

**Comment by martynabogacz** [comment]
Not sure what is happening but the book doesn't even compile for me locally. It says that status of bokdown_demo.Rmd is 'untracked'.

**Comment by andysouth** [comment]
Does the fact that it is working on dev-sf (link below) suggest that this is a system problem rather than something we have done ?
https://github.com/afrimapr/afrimapr-book/runs/2458768279?check_suite_focus=true

It is working for me locally on windows too.

Any suggestions @Robinlovelace ?

**Comment by andysouth** [comment]
The error started at the same time that this bookdown commit was made, not sure if that is a coincidence : 

https://github.com/rstudio/bookdown/commit/dfc4f1fb04a7ead9c462e40180f0c3a5dbc212c9

**Comment by andysouth** [comment]
This error first appeared in this scheduled job (seemingly when no code or test had changed)
https://github.com/afrimapr/afrimapr-book/runs/2416618459?check_suite_focus=true

**Comment by andysouth** [comment]
CRAN version of bookdown did changed at same time this started happening.
  
Suspect it comes from this : https://github.com/afrimapr/afrimapr-book/blob/main/tic.R

which calls : https://github.com/ropensci/tic/blob/278e3e9a41109e7296a14ce5c43d2c4d82e12954/R/steps-bookdown.R

which calls : https://github.com/rstudio/bookdown/blob/master/R/render.R

**Comment by Robinlovelace** [comment]
Hi all, picking up on this now...

If it's an issue with bookdown you could install a specific version of the package before building.

However, I suggest trying a different .yml file first as it may be related to `tic` as you say. This could be a good first port of call: https://gist.github.com/matteodelucchi/c8d3e584387bf6980411c03e05283d31

**Comment by Robinlovelace** [comment]
There's also good info in the blog post: https://ropensci.org/blog/2020/04/07/bookdown-learnings/

Happy to take a look if there's no quick fix but a busy week and going on holiday on Friday afternoon.

**Comment by andysouth** [comment]
Thanks @Robinlovelace.
@martynabogacz could you have a quick look at Robins suggestions and see if there is a quick fix ? If not I can have a look later in the week :-)

**Comment by Robinlovelace** [comment]
Otherwise I can look next week. As long as it builds locally we can get it working, no need to waste lots of time looking at this at this stage...

**Comment by martynabogacz** [comment]
Yes, I will have a look if this can be addressed with Robin's suggestions. No worries.

**Comment by andysouth** [comment]
Hi @Robinlovelace would you like to meet one evening this week for a minihack to try to fix this ? 

@martynabogacz & I tried a couple of things but no joy yet.

**Comment by Robinlovelace** [comment]
Hi @andysouth I'm on holiday until Thursday next week and pretty busy then so w/c 7th may be best.

**Comment by Robinlovelace** [comment]
Will try this: https://github.com/hadley/r-pkgs/blob/master/.github/workflows/build-book.yaml

**Comment by Robinlovelace** [comment]
Latest issue is a bit bamboozling: https://github.com/afrimapr/afrimapr-book/runs/2777645864#step:5:33

**Comment by Robinlovelace** [comment]
Heads-up I think this may have been the cause of build fails: https://github.com/afrimapr/afrimapr-book/commit/c5c9dfe121b94b3d4867d7fd3d22f2f0e38252f4

**Comment by andysouth** [comment]
Thanks Robin, we put the version < in because evidence suggested that the
earlier failure was due to a bookdown update interacting with tic. It
didn't fix though. You're right that now we've moved away from tic we
definitely don't need :-)

**Comment by Robinlovelace** [comment]
> Thanks Robin, we put the version < in because evidence suggested that the

Yes but it was added incorrectly:

```
bookdown(< x)
```

is wrong, there should have been a space after the `n`.

We're hitting another easier-to-debug issue now: `units` needs to be installed on Mac. Solution can be found here: https://github.com/r-quantities/units/blob/master/.github/workflows/build.yml#L57

**Comment by andysouth** [comment]
Thanks @Robinlovelace I'll start that as a new issue :-)

**Comment by andysouth** [comment]
This issue was avoided by moving away from tic to a Netlify deployment. started in #24 working by #31

**Comment by andysouth** [comment]
tic & appveyor yml files removed #32

**Comment by Robinlovelace** [comment]
:tada: great work Andy and Martyna!
