### ISSUE TITLE
add github actions secrets

### ISSUE THREAD

**Issue by andysouth** [afrimapr/afrimapr-book#25]
Seems I need to add these specified in the new yaml in #24. Thanks @Robinlovelace 👍 

      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

How to add github actions secrets :
https://lannonbr.com/blog/github-actions-secrets

**Comment by andysouth** [comment]
Further instructions : 
https://github.com/marketplace/actions/netlify-deploy-action

**Comment by andysouth** [comment]
This suggests that the GITHUB_TOKEN may be there automatically so I don't need to add it.
https://docs.github.com/en/actions/reference/authentication-in-a-workflow

**Comment by andysouth** [comment]
More complete instructions for deploying book to Netlify via Github Actions : 
https://www.hvitfeldt.me/blog/bookdown-netlify-github-actions/

**Comment by andysouth** [comment]
I've added the two netlify secrets and created the site here : 

https://afrimapr-book.netlify.app/

Have to go now. Do you know what we need to do next @Robinlovelace ? :-)

**Comment by Robinlovelace** [comment]
> Do you know what we need to do next @Robinlovelace ? :-)

Fix #23. That involves adding system deps for the `units` library for Mac. Shouldn't be too hard.
