### ISSUE TITLE
syntax error near unexpected token `"sf",' from Actions

### ISSUE THREAD

**Issue by andysouth** [afrimapr/afrimapr-book#28]
https://github.com/afrimapr/afrimapr-book/runs/2793152715#step:7:271

Associated with 

https://github.com/afrimapr/afrimapr-book/blob/7b51d97d3c3fd839ca6995aa8a12e845bd89e58f/.github/workflows/build-book.yaml#L57

which was added to try to fix Mac installation issues following from #27 

It comes from the readme page of sf and looks to be same syntax as line38 just above it.

@Robinlovelace could you have a look ?

**Comment by Robinlovelace** [comment]
I think we should use .yaml files that work with Mac, if we use the binary version that shouldn't be necessary. It may take a day or so for the binary version to be released for Mac which will I think make those config args redundent.

**Comment by andysouth** [comment]
seemingly fixed, now replaced by #29

**Comment by Robinlovelace** [comment]
It's like whack-a-mole! Good luck @andysouth and great debugging work :construction:
