### ISSUE TITLE
Error: Shape contains invalid polygons. Please fix it or set tmap_options(check.and.fix = TRUE)

### ISSUE THREAD

**Issue by andysouth** [afrimapr/afrimapr-book#30]
With book compilation online - but good at least that it reached this stage :-)

This is a similar error that we are seeing on RStudio cloud with afrilearndata africountries specifically the Sudan polygon.

Seemed to be related to recent change to sf - didn't occur on my local windows machine even though it also had most recent version of sf.

Trying to fix today.

**Comment by martynabogacz** [comment]
Adding the following bit of code, before trying to plot the map switches off the spherical geometry and deals with this issue :

```{r}
sf_use_s2(FALSE)
```

Solution source: https://github.com/r-spatial/sf/issues/1649
