### ISSUE TITLE
Problem with "Copy" when building the book

### ISSUE THREAD

**Issue by martynabogacz** [afrimapr/afrimapr-book#31]
There apparently a missing file or directory, see here: https://github.com/afrimapr/afrimapr-book/runs/2898697911#step:13:13

Potential reason: _redirects does not have an file extension as per Netlify's documentation. I use a workaround: cp _redirects after Mix. as suggsted here: https://github.com/JeffreyWay/laravel-mix/issues/1450

**Comment by andysouth** [comment]
Seems to be due to this line :         run: cp _redirects _book/
here : https://github.com/afrimapr/afrimapr-book/blob/d24970f96b3a8b85d927436c92195f9579550d7e/.github/workflows/build-book.yaml#L85

**Comment by andysouth** [comment]
Seems that where Robin got this file from there is a _redirects folder that we do not have. So tried commenting out that copy step above.

https://github.com/hadley/r-pkgs/blob/29c9fbba1ec9df084d837711c29bd87c82d1c469/.github/workflows/build-book.yaml

https://github.com/hadley/r-pkgs/blob/master/_redirects

**Comment by andysouth** [comment]
Commenting out the Copy section above fixed this. Now the book successfully deploys to Netlify, hurrah !
