### ISSUE TITLE
install.packages() in chapter chunks ?

### ISSUE THREAD

**Issue by andysouth** [afrimapr/afrimapr-book#33]
do we want any use of install.packages() in chapter content, or should it all be dealt with in the Description file ? 
What is good practice ?

**Comment by martynabogacz** [comment]
One of the options could be to keep code chunks with install.packages () and eval = FALSE, to make sure readers are aware of this important step but it is not executed.

**Comment by Robinlovelace** [comment]
I think there's no harm in writing 

`install.packages("vitalPackage")`

in the text, as long as it's not evaluated and adds to the message that the package needs to be installed. However, I think it may be slightly better to just say something like

```
Ensure that you have installed the `vitalPackage` package before running the code in this chapter.
```
