### ISSUE TITLE
Problem with credentials 

### ISSUE THREAD

**Issue by martynabogacz** [afrimapr/afrimapr-book#38]
Hi,

I am not able to compile the book due to some problems with credetials as showed here: https://github.com/afrimapr/afrimapr-book/runs/3595840821?check_suite_focus=true#step:4:6 

I tried adding personal PAT but it didn't help. Can you please have a look into this as an admin? Maybe that would help?

Thanks

**Comment by andysouth** [comment]
Thanks Martyna, I'll have a look at this before tomorrow :-)

**Comment by andysouth** [comment]
This error disappeared when we removed dev-sf.yaml which was a previous workflow that it turned out we didn't need anymore !
