### ISSUE TITLE
Work out how to make intro chap1 (not chap2)

### ISSUE THREAD

**Issue by andysouth** [afrimapr/afrimapr-book#4]
I suspect by editing text here. Athough when I set to e.g. ##Preface that caused book creation to fail

https://github.com/afrimapr/book/blob/b8e6b945cf4bb39ae8a54e7304ffa97246a51d0b/index.Rmd#L15

Follow some magic from here :
https://github.com/Robinlovelace/geocompr/blob/master/index.Rmd

**Comment by Robinlovelace** [comment]
You can make the preface chapter like this:

```
# Preface {-}
```

To avoiding that from being Chapter 1: https://bookdown.org/yihui/rmarkdown-cookbook/unnumbered-sections.html

**Comment by martynabogacz** [comment]
Thanks both,

I will make preface without number and into as a first chapter. Robin, thanks for your suggestion - will try it.
And then, I will modify chapters according to the list in the preface, I will keep the preface too as a list of content for now.

(Just making sure I understand everything correctly.)

Many thanks,

Martyna
________________________________
