### ISSUE TITLE
change repo name to afrimapr-book or similar

### ISSUE THREAD

**Issue by andysouth** [afrimapr/afrimapr-book#5]
Can we change the repo name to afrimapr-book or book-afrimapr so it is more informative when people clone ?

**Comment by Robinlovelace** [comment]
> Can we change the repo name to afrimapr-book or book-afrimapr so it is more informative when people clone ?

Of the two afrimapr-book would get my vote : )

**Comment by andysouth** [comment]
Repo renamed to afrimapr-book and deploy error fixed by modifying tic.yml
