### ISSUE TITLE
Problem with the deployment

### ISSUE THREAD

**Issue by martynabogacz** [afrimapr/afrimapr-book#7]
Hi, 

I was trying to publish this chunk of executable code becuase it works locally but then it fails at the deployment stage. I was trying to do some backward engeneering and I noticed that as soon as I include r within the curly brackets for the code chunks then it fails. 

**See the whole code below:**

Install required packages

```{r, results=FALSE, message=FALSE}
install.packages(c("ggplot2","sf", "rnaturalearth", "rnaturalearthdata"))
```

Load the packages

```{r, results=FALSE, message=FALSE}
library(ggplot2)
library(sf)
library(rnaturalearth)
library(rnaturalearthdata)
library(dplyr)
```
Create a dataset
```{r, results=FALSE, message=FALSE}
africa <- ne_countries(continent = 'africa', scale = "medium", returnclass = "sf")
```
### Static maps
Map with colour fill based on the continuous variable
```{r}
ggplot(africa) + 
  geom_sf(aes(fill=lastcensus)) + 
  coord_sf(datum = NA) + 
  labs(fill = "Last census") +
  theme_minimal()
```

Crate a categorical variable
```{r, results=FALSE, message=FALSE}
africa <- africa %>%
  mutate(cuts = case_when(
    lastcensus <= 1970 ~ "1970 or earlier",
    lastcensus > 1970 & lastcensus <= 2002 ~ "between 1970 and 2002",
    lastcensus > 2002 & lastcensus <= 2008 ~ "between 2002 and 2008",
    lastcensus > 2008 & lastcensus <= 2010 ~ "between 2008 and 2010",
    lastcensus > 2010 & lastcensus <= 2012 ~ "between 2010 and 2012"))
```
Map with colour fill based on the categorical variable
```{r}
ggplot(africa) + 
  geom_sf(aes(fill=cuts)) + 
  coord_sf(datum = NA) + 
  theme_minimal() +
  labs(fill = "Last census") +
  scale_fill_manual(values = c("red4", "red1", "tomato1", "gold","darkolivegreen2"))
```

**Comment by Robinlovelace** [comment]
Hi Martyna, thanks for the clear issue report. I think I know what is causing the issue from the error logs here (you can see this by clicking on the :x: next the commits   ): https://github.com/afrimapr/afrimapr-book/runs/1529080808.

The issue seems to have been:

```r
there is no package called 'dplyr'
```

From this line: https://github.com/afrimapr/afrimapr-book/runs/1529080808#step:19:130

I will try to get it working.

**Comment by Robinlovelace** [comment]
Think that has been fixed :tada: 

Result: https://afrimapr.github.io/afrimapr-book/visualising-1.html

**Comment by martynabogacz** [comment]
Wow! Amazing, thanks a lot.

Martyna

On 10.12.2020, at 18:35, Robin <notifications@github.com> wrote:

﻿

Think that has been fixed 🎉

Result: https://afrimapr.github.io/afrimapr-book/visualising-1.html
